# Generated by Django 4.2.30 on 2026-09-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='vaya',
            field=models.CharField(choices=[('bala', 'Bala (childhood: up to 16 years)'), ('madhya', 'Madhya (middle age: 16-70 years)'), ('vriddha', 'Vriddha (old age: above 70 years)')], max_length=20),
        ),
    ]
