# Generated by Django 4.2.30 on 2026-09-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_patient_vaya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ahara_shakti',
            field=models.CharField(choices=[('pravara', 'Pravara'), ('madhyama', 'Madhyama'), ('avara', 'Avara')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prakriti',
            field=models.CharField(choices=[('vata', 'Vata (Air + Space)'), ('pitta', 'Pitta (Fire + Water)'), ('kapha', 'Kapha (Earth + Water)'), ('vata_pitta', 'Vata-Pitta (Air-Space + Fire-Water)'), ('pitta_kapha', 'Pitta-Kapha (Fire-Water + Earth-Water)'), ('vata_kapha', 'Vata-Kapha (Air-Space + Earth-Water)'), ('tridoshaja', 'Tridoshaja (all three balanced)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pramana',
            field=models.CharField(choices=[('pravara', 'Pravara'), ('madhyama', 'Madhyama'), ('avara', 'Avara')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='samhanana',
            field=models.CharField(choices=[('pravara', 'Pravara'), ('madhyama', 'Madhyama'), ('avara', 'Avara')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sara',
            field=models.CharField(choices=[('pravara', 'Pravara'), ('madhyama', 'Madhyama'), ('avara', 'Avara')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='satmya',
            field=models.CharField(choices=[('pravara', 'Pravara'), ('madhyama', 'Madhyama'), ('avara', 'Avara')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='satva',
            field=models.CharField(choices=[('pravara', 'Pravara'), ('madhyama', 'Madhyama'), ('avara', 'Avara')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='vikriti',
            field=models.CharField(choices=[('vata', 'Vata Vikriti (Air + Space)'), ('pitta', 'Pitta Vikriti (Fire + Water)'), ('kapha', 'Kapha Vikriti (Earth + Water)'), ('dwidoshaja', 'Dwidoshaja (two doshas involved)'), ('sannipataja', 'Sannipataja (all three doshas involved)'), ('none', 'No significant Vikriti')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='vyayama_shakti',
            field=models.CharField(choices=[('pravara', 'Pravara'), ('madhyama', 'Madhyama'), ('avara', 'Avara')], max_length=20),
        ),
    ]
