# Generated by Django 4.2.30 on 2026-09-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_prescription_doctor_user_token_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='appointment_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
