# Generated by Django 4.2.30 on 2026-09-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_token_appointment_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='abha',
        ),
        migrations.AddField(
            model_name='patient',
            name='abha_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='abha_number',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='date',
            field=models.DateField(),
        ),
    ]
