# Generated by Django 4.2.30 on 2026-09-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_patient_abha_patient_abha_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='abha_verified',
            field=models.BooleanField(default=False),
        ),
    ]
