# Generated by Django 4.2.30 on 2026-09-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_abdmtoken_patient_abha_verified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('seen', 'Seen'), ('cancelled', 'Cancelled')], default='waiting', max_length=10),
        ),
    ]
