# Generated by Django 4.2.30 on 2026-09-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_token_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(fields=('doctor', 'date', 'token_number'), name='unique_token_per_doctor_per_date'),
        ),
    ]
