# Generated by Django 4.2.30 on 2026-09-14 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_patient_contact_patient_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non_pain_symptoms', models.JSONField(blank=True, default=list)),
                ('fever_temperature', models.CharField(blank=True, max_length=50)),
                ('fever_duration', models.CharField(blank=True, max_length=50)),
                ('other_symptoms', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_record', to='myapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PainSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('site', models.TextField(blank=True)),
                ('onset', models.TextField(blank=True)),
                ('character', models.TextField(blank=True)),
                ('radiation', models.TextField(blank=True)),
                ('associations', models.TextField(blank=True)),
                ('time_course', models.TextField(blank=True)),
                ('exacerbating_relieving', models.TextField(blank=True)),
                ('severity', models.CharField(blank=True, max_length=20)),
                ('symptom_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pain_symptoms', to='myapp.symptom')),
            ],
        ),
    ]
