# Generated by Django 6.1.1 on 2026-09-17 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_symptom_painsymptom'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField(blank=True)),
                ('symptoms', models.JSONField(blank=True, default=list)),
                ('other_symptoms', models.TextField(blank=True)),
                ('fever_temperature', models.CharField(blank=True, max_length=50)),
                ('fever_duration', models.CharField(blank=True, max_length=50)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='myapp.patient')),
            ],
        ),
    ]
