# Generated by Django 4.2.30 on 2026-09-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_patient_user_medicaldocument'),
    ]

    operations = [
    ]
