# Generated by Django 4.2.30 on 2026-09-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20260918_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='dbp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='hr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='rr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='saturation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='sbp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='triage_level',
            field=models.PositiveIntegerField(blank=True, help_text='KTAS priority level (1: Critical to 5: Non-Urgent)', null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='triage_recommendation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
