# Generated by Django 4.2.30 on 2026-09-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_symptom_dbp_symptom_hr_symptom_rr_symptom_saturation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='visit_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
