# Generated by Django 4.2.30 on 2026-09-22 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_patienthistory_visit_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_history', to='myapp.token'),
        ),
    ]
